"""
t05 — IRT (2PL) calibration for item difficulty labelling.

Reads responses from outputs/irt_baseline/ (generated by qa_runner.py with
model=Mistral-7B, all items, seed=42) and fits a 2-parameter logistic IRT model
using py-irt (or girth as fallback).

Outputs:
  data/item_bank/{qtype}/items_with_difficulty.jsonl  — items with irt_b, difficulty label
  outputs/irt_calibration_report.csv                  — per-item IRT parameters

Usage:
    # Step 1: generate Mistral-7B baseline responses (run once)
    python src/generation/qa_runner.py --model mistralai/Mistral-7B-Instruct-v0.3 \
        --backend vllm --qtypes MCQ TF Fill SA --seeds 42 \
        --output-dir outputs/irt_baseline --phase irt_baseline

    # Step 2: fit IRT and label difficulty
    python src/data/irt_calibration.py --responses outputs/irt_baseline --qtype MCQ
    python src/data/irt_calibration.py --responses outputs/irt_baseline --qtype TF
    python src/data/irt_calibration.py --responses outputs/irt_baseline --qtype Fill
    python src/data/irt_calibration.py --responses outputs/irt_baseline --qtype SA
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

BANK_ROOT = Path("data/item_bank")
OUTPUT_DIR = Path("outputs")

DIFFICULTY_THRESHOLDS = (-0.5, 0.5)  # b < -0.5 → Easy; b > 0.5 → Hard; else Medium


def load_responses(responses_dir: Path, qtype: str) -> pd.DataFrame:
    """Load all response JSONs for a given qtype into a DataFrame."""
    rows = []
    pattern = f"**/*_{qtype}_*.json"
    for p in responses_dir.glob(pattern):
        try:
            data = json.loads(p.read_text())
        except Exception:
            continue
        for resp in data.get("responses", [data]):
            rows.append({
                "item_id": resp.get("item_id"),
                "model_id": resp.get("model_id", ""),
                "seed": resp.get("seed", 0),
                "correct": int(resp.get("correct", 0)),
            })
    return pd.DataFrame(rows)


def build_response_matrix(df: pd.DataFrame) -> tuple[np.ndarray, list[str]]:
    """Pivot to item × person binary response matrix."""
    df["person"] = df["model_id"] + "_seed" + df["seed"].astype(str)
    pivot = df.pivot_table(index="person", columns="item_id", values="correct", aggfunc="max")
    pivot = pivot.fillna(0).astype(int)
    item_ids = list(pivot.columns)
    matrix = pivot.values  # shape: (persons, items)
    return matrix, item_ids


def fit_2pl(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Fit 2PL IRT model.
    Returns arrays of discrimination (a) and difficulty (b) per item.
    Prefers py-irt; falls back to simple p-value approximation.
    """
    try:
        from py_irt.training import IRTModelTrainer
        from py_irt.config import IrtConfig

        config = IrtConfig(model="2pl", epochs=1000, device="cpu")
        trainer = IRTModelTrainer(config=config)
        trainer.train(matrix)
        params = trainer.best_params
        a = np.array(params["disc"])
        b = np.array(params["diff"])
        return a, b
    except ImportError:
        pass

    try:
        from girth import twopl_mml
        result = twopl_mml(matrix.T)
        return result["Discrimination"], result["Difficulty"]
    except ImportError:
        pass

    p_correct = matrix.mean(axis=0)
    p_correct = np.clip(p_correct, 0.05, 0.95)
    b_approx = -np.log(p_correct / (1 - p_correct))
    a_approx = np.ones_like(b_approx)
    print("  [WARN] py-irt and girth both missing — using p-value approximation for difficulty.")
    print("  Install: pip install py-irt   or   pip install girth")
    return a_approx, b_approx


def label_difficulty(b: float) -> str:
    lo, hi = DIFFICULTY_THRESHOLDS
    if b < lo:
        return "Easy"
    elif b > hi:
        return "Hard"
    return "Medium"


def apply_irt_to_bank(item_ids: list[str], a: np.ndarray, b: np.ndarray,
                      qtype: str) -> pd.DataFrame:
    items_path = BANK_ROOT / qtype.lower() / "items.jsonl"
    items = [json.loads(l) for l in items_path.open()]

    irt_map = {iid: (float(a[i]), float(b[i])) for i, iid in enumerate(item_ids)}

    enriched = []
    for item in items:
        iid = item["item_id"]
        if iid in irt_map:
            item["irt_a"] = round(irt_map[iid][0], 4)
            item["irt_b"] = round(irt_map[iid][1], 4)
            item["difficulty"] = label_difficulty(irt_map[iid][1])
        else:
            item["irt_a"] = None
            item["irt_b"] = None
            item["difficulty"] = item.get("difficulty_raw", "Medium") or "Medium"
        enriched.append(item)

    out_path = BANK_ROOT / qtype.lower() / "items_with_difficulty.jsonl"
    with out_path.open("w") as f:
        for item in enriched:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")
    print(f"  Wrote {len(enriched)} items with IRT labels → {out_path}")

    report_rows = [{"item_id": iid, "irt_a": a[i], "irt_b": b[i],
                    "difficulty": label_difficulty(b[i])}
                   for i, iid in enumerate(item_ids)]
    return pd.DataFrame(report_rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="2PL IRT calibration for item bank")
    parser.add_argument("--responses", required=True,
                        help="Directory containing baseline response JSON files")
    parser.add_argument("--qtype", required=True, choices=["MCQ", "TF", "Fill", "SA"])
    args = parser.parse_args()

    responses_dir = Path(args.responses)
    print(f"Loading responses from {responses_dir} for qtype={args.qtype}")

    df = load_responses(responses_dir, args.qtype)
    if df.empty:
        print("No responses found. Run qa_runner.py with --phase irt_baseline first.")
        return

    print(f"  {len(df)} response records | {df['item_id'].nunique()} unique items")
    matrix, item_ids = build_response_matrix(df)
    print(f"  Response matrix: {matrix.shape[0]} persons × {matrix.shape[1]} items")

    a, b = fit_2pl(matrix)
    report_df = apply_irt_to_bank(item_ids, a, b, args.qtype)

    report_path = OUTPUT_DIR / f"irt_calibration_{args.qtype}.csv"
    report_df.to_csv(report_path, index=False)
    print(f"  IRT report → {report_path}")

    counts = report_df["difficulty"].value_counts()
    print(f"  Difficulty distribution:\n{counts.to_string()}")


if __name__ == "__main__":
    main()
