"""
Teacher vignette study — qualitative analysis support.

Phase 6 (Decision Log D9 amendment): 4-6 practising mathematics teachers (Grades 7-9)
evaluate one anonymised dialogue excerpt per condition in a 30-minute remote interview.

This script:
  1. Selects representative dialogue excerpts (1 per condition) for teacher review
  2. Produces vignette packets (anonymised, condition-blind)
  3. Provides coding scaffold for thematic analysis of interview transcripts
  4. Aggregates teacher ratings and themes into a summary CSV

Interview protocol:
  - Show dialogue (printed or shared screen)
  - Ask: "Does this student seem like a real 7th/8th grade math student? Why or why not?"
  - Ask: "If you were tutoring this student, what would you do next?"
  - Ask: "Can you imagine using this type of dialogue in your professional development or
         curriculum planning? What would you use it for?"

Thematic codes (provisional; refine during analysis):
  T1: Structure as authenticity cue — teacher attributes authenticity to structured errors/questions
  T2: Questioning as teachability signal — asking questions rated positively for teaching
  T3: Over-competence recognition — teacher identifies C4 as "not a student" quickly
  T4: Appropriate epistemic humility — targeted uncertainty rated higher than global confusion
  T5: Emotional/motivational gap — teacher notes lack of affect, motivation cues

Usage:
  # Select vignette excerpts
  python src/qual/teacher_vignette_analysis.py --select-excerpts

  # After interview transcripts collected, analyse themes
  python src/qual/teacher_vignette_analysis.py --analyse-themes --transcripts data/vignette_transcripts/
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

import pandas as pd

DIMENSIONS = ["TA1", "TA2", "TA3", "TA4", "SS1", "SS2", "SS3", "SS4", "SS5"]
THEMATIC_CODES = {
    "T1": "Structure as authenticity cue",
    "T2": "Questioning as teachability signal",
    "T3": "Over-competence recognition",
    "T4": "Appropriate epistemic humility",
    "T5": "Emotional/motivational gap",
    "T6": "Diagnostic value",     # teacher sees C2 as useful for misconception diagnosis
    "T7": "Usability for PD",     # teacher imagines using dialogue in professional development
    "T8": "Frustration with vagueness",  # generic C3 frustrating for teachers
}

VIGNETTE_HEADER = """\
╔══════════════════════════════════════════════════════════════════════╗
║  TEACHER VIGNETTE — ID: {vignette_id}                               ║
║  Study: LLM Simulated Learner Evaluation                            ║
║  This dialogue was generated by an AI system. You will evaluate it. ║
╚══════════════════════════════════════════════════════════════════════╝

PROBLEM:
{problem}

STUDENT'S INITIAL ANSWER:
{initial_answer}

───────────────────────────────────────────────────────────────────────
DIALOGUE TRANSCRIPT (first 6 turns shown)
───────────────────────────────────────────────────────────────────────
{transcript}
───────────────────────────────────────────────────────────────────────

INTERVIEW QUESTIONS:
1. Does this student seem like a real 7th/8th grade math student?
   What makes you say that?

2. If you were the tutor in this conversation, what would you do next?

3. Could you imagine using this type of dialogue in professional
   development or curriculum planning? How?

4. Rate this dialogue (1 = not at all student-like, 5 = very student-like):
   Rating: ___   Brief reason: ________________________________

END OF VIGNETTE {vignette_id}
"""

INTERVIEW_RECORDING_TEMPLATE = """\
# Teacher Vignette Interview Record

**Teacher ID**: T_{teacher_id:02d}
**Date**: {date}
**Vignette IDs shown**: {vignette_ids}
**Interviewer**: [NAME]
**Duration**: ___ minutes

---

## Q1: Does this student seem real? (per vignette)

| Vignette | Response Summary | Authenticity Rating (1-5) |
|----------|-----------------|--------------------------|
"""

THEME_CODING_SCAFFOLD = """\
# Thematic Analysis Coding Scaffold

## Thematic Code Definitions
{codes}

## Coding Instructions
1. Read each interview segment.
2. Identify all applicable codes (multiple codes per segment allowed).
3. Note the vignette ID associated with each coded segment.
4. Note supporting quote (verbatim, 1-2 sentences).

## Coding Sheet

| Segment_ID | Teacher_ID | Vignette_ID | Code(s) | Quote | Memo |
|------------|------------|-------------|---------|-------|------|
"""


def select_vignette_excerpts(
    phase: str = "main",
    n_turns: int = 6,
    seed: int = 2026,
    output_dir: Path = Path("outputs/vignette_packets"),
) -> None:
    """Select one representative dialogue per condition for teacher vignette packets."""
    output_dir.mkdir(parents=True, exist_ok=True)
    base = Path("outputs") / phase
    rng = random.Random(seed)

    manifest_rows = []
    for cond in ["C1", "C2", "C3", "C4"]:
        cond_dirs = list(base.rglob(f"*/{cond}"))
        if not cond_dirs:
            cond_dirs = [base / cond]

        candidates = []
        for d in cond_dirs:
            if d.is_dir():
                candidates.extend(list(d.glob("*.json")))

        if not candidates:
            print(f"WARNING: No dialogues found for {cond} in {base}")
            continue

        # Filter: valid, medium-length dialogues
        valid = []
        for jf in candidates:
            try:
                data = json.loads(jf.read_text())
                if not data.get("exclusion_flag") and len(data.get("turns", [])) >= 4:
                    valid.append((jf, data))
            except Exception:
                continue

        if not valid:
            continue

        rng.shuffle(valid)
        jf, data = valid[0]

        turns = data.get("turns", [])[:n_turns]
        problem = ""
        for line in data.get("system_prompt", "").splitlines():
            if line.strip() and not line.startswith("You are"):
                problem = line.strip()[:200]
                break

        initial_answer = turns[0].get("learner_turn", "")[:200] if turns else ""

        transcript_lines = []
        for t in turns:
            if t.get("tutor_turn"):
                transcript_lines.append(f"[TUTOR]:   {t['tutor_turn']}")
            if t.get("learner_turn"):
                # Remove leakage
                lr = t["learner_turn"]
                for phrase in ["these instructions", "REQUIRED", "system prompt", "I am simulating"]:
                    lr = lr.replace(phrase, "[...]")
                transcript_lines.append(f"[LEARNER]: {lr}")
            transcript_lines.append("")

        vignette_id = f"V{cond}_{data.get('seed', 0)}"
        packet_text = VIGNETTE_HEADER.format(
            vignette_id=vignette_id,
            problem=problem or "(math word problem)",
            initial_answer=initial_answer or "(see first learner turn)",
            transcript="\n".join(transcript_lines),
        )

        out_path = output_dir / f"{vignette_id}_vignette.txt"
        out_path.write_text(packet_text)
        manifest_rows.append({
            "vignette_id": vignette_id,
            "condition": cond,
            "scenario_id": data.get("scenario_id"),
            "model_tag": data.get("model_tag"),
            "json_path": str(jf),
        })
        print(f"  Vignette {vignette_id} → {out_path}")

    manifest_df = pd.DataFrame(manifest_rows)
    manifest_df.to_csv(output_dir / "vignette_manifest.csv", index=False)
    print(f"\nVignette manifest → {output_dir}/vignette_manifest.csv")
    print(f"Share vignette_*.txt files with teachers (NOT the manifest).")

    # Write theme coding scaffold
    codes_text = "\n".join([f"  {k}: {v}" for k, v in THEMATIC_CODES.items()])
    scaffold = THEME_CODING_SCAFFOLD.format(codes=codes_text)
    scaffold_path = output_dir / "theme_coding_scaffold.md"
    scaffold_path.write_text(scaffold)
    print(f"Theme coding scaffold → {scaffold_path}")


def analyse_themes(transcripts_dir: Path) -> None:
    """
    Aggregate coded interview transcripts into theme frequency table.
    Expects CSV files in transcripts_dir with columns:
      Segment_ID, Teacher_ID, Vignette_ID, Code(s), Quote, Memo
    """
    coding_files = list(transcripts_dir.glob("*.csv"))
    if not coding_files:
        print(f"No coding CSV files found in {transcripts_dir}")
        return

    dfs = [pd.read_csv(f) for f in coding_files]
    df = pd.concat(dfs, ignore_index=True)

    # Normalise Code(s) column — may contain comma-separated codes
    rows = []
    for _, row in df.iterrows():
        codes_raw = str(row.get("Code(s)", "")).replace(" ", "")
        for code in codes_raw.split(","):
            code = code.strip()
            if code:
                rows.append({
                    "teacher_id": row.get("Teacher_ID"),
                    "vignette_id": row.get("Vignette_ID"),
                    "code": code,
                    "code_label": THEMATIC_CODES.get(code, "unknown"),
                    "quote": row.get("Quote", ""),
                })

    code_df = pd.DataFrame(rows)
    freq = code_df.groupby(["vignette_id", "code", "code_label"]).size().reset_index(name="count")
    freq.to_csv(Path("outputs/teacher_vignette_theme_frequencies.csv"), index=False)

    summary = (
        code_df.groupby(["code", "code_label"])
        .agg(n_instances=("teacher_id", "count"), n_teachers=("teacher_id", "nunique"))
        .reset_index()
        .sort_values("n_instances", ascending=False)
    )
    summary.to_csv(Path("outputs/teacher_vignette_theme_summary.csv"), index=False)
    print("\n=== THEMATIC ANALYSIS SUMMARY ===")
    print(summary.to_string(index=False))
    print("\nFull frequency table → outputs/teacher_vignette_theme_frequencies.csv")


def main() -> None:
    parser = argparse.ArgumentParser(description="Teacher vignette study support")
    parser.add_argument("--select-excerpts", action="store_true")
    parser.add_argument("--analyse-themes", action="store_true")
    parser.add_argument("--phase", default="main")
    parser.add_argument("--transcripts", default="data/vignette_transcripts")
    parser.add_argument("--n-turns", type=int, default=6)
    args = parser.parse_args()

    if args.select_excerpts:
        select_vignette_excerpts(phase=args.phase, n_turns=args.n_turns)

    if args.analyse_themes:
        transcripts_dir = Path(args.transcripts)
        if not transcripts_dir.exists():
            print(f"Transcripts directory not found: {transcripts_dir}")
            print("Create the directory and place coded CSV files there first.")
        else:
            analyse_themes(transcripts_dir)

    if not args.select_excerpts and not args.analyse_themes:
        parser.print_help()


if __name__ == "__main__":
    main()
